### ISSUE TITLE
Package broken

### ISSUE THREAD

**Issue by 89z** [siongui/instago#6]
Using this program:

~~~go
package main

import (
   "fmt"
   "github.com/siongui/instago"
)

func main() {
   m, err := instago.GetPostInfoNoLogin("CT-cnxGhvvO")
   if err != nil {
      panic(err)
   }
   fmt.Printf("%+v\n", m)
}
~~~

I get this result:

~~~
panic: https://www.instagram.com/p/CT-cnxGhvvO/?__a=1
resp.StatusCode: 429
~~~

**Comment by siongui** [comment]
HTTP 429 means [too many requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429). This response is from Instagram servers and nothing to do with the package.

**Comment by 89z** [comment]
Thats a silly comment, as this is literally the first time I used this package, ever.

Plus the same exact URL works in my browser.

**Comment by 89z** [comment]
Looks like problem was the User-Agent. I implemented my own package, because of poor response here:

https://github.com/89z/mech/blob/master/instagram/instagram.go

**Comment by 89z** [comment]
Problem is here:

https://github.com/siongui/instago/blob/c389db73a91b9cfae98f821c89624a2863dce6f5/httpresp.go#L39-L41

package should be sending a custom User-Agent such as `Mozilla` or similar.

**Comment by siongui** [comment]
You are correct. I thought I already allow setting custom User Agent in the method. It is fixed in the commit. Please report if you still have problems.

**Comment by siongui** [comment]
> Problem is here:
> 
> https://github.com/siongui/instago/blob/c389db73a91b9cfae98f821c89624a2863dce6f5/httpresp.go#L39-L41
> 
> package should be sending a custom User-Agent such as `Mozilla` or similar.

You are correct. I thought I already allow setting custom User Agent in the method. It is fixed in the commit. Please report if you still have problems.

**Comment by 89z** [comment]
~~~
panic: invalid character '<' looking for beginning of value
~~~

**Comment by siongui** [comment]
> ```
> panic: invalid character '<' looking for beginning of value
> ```

This error comes from instago failed to parse the HTML because Instagram redirect the user to login page. This means you already made too many request anonymously so Instagram asked you to login. You can not use the -NoLogin method if you see this panic message.

**Comment by 89z** [comment]
I only did 5 requests...
